# Generated by Django 5.0.1 on 2024-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_skills',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='professional_skills',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
