# Generated by Django 5.0.1 on 2024-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='desc',
        ),
        migrations.AddField(
            model_name='skills',
            name='persent',
            field=models.IntegerField(null=True),
        ),
    ]
