# Generated by Django 5.0.1 on 2024-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_skills_desc_skills_persent'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_skills',
            name='datetime',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional_skills',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
