# Generated by Django 5.0.1 on 2024-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_professional_skills_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_skills',
            name='datetime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
