# Generated by Django 5.0.1 on 2024-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='about_me',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
