# Generated by Django 5.0.1 on 2024-01-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_personal_info_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='age',
            field=models.IntegerField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='field',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='phone_number',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
