# Generated by Django 5.0.1 on 2024-01-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_work_experience_date_work_experience_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='work_experience',
            new_name='education',
        ),
    ]
