# Generated by Django 5.0.1 on 2024-01-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_rename_work_experience_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Skills_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('datetime', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
