# Generated by Django 5.0.1 on 2024-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_professional_skills_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('persent', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Professional_Skills_2',
        ),
    ]
